# Generated by Django 4.2.1 on 2023-06-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productimage_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variant_price",
                to="product.product",
            ),
        ),
    ]
